---
title: "Método cientifico. Manipulación de datos."
author: "Aleksander Dietrichson, PhD"
format: 
  revealjs: 
    code-line-numbers: false
    echo: true
    theme: dark
    chalkboard: true
editor: visual
---

## Agenda de hoy

-   El método científico

    -   Formular hipótesis

    -   Estrategia de evaluación

    -   La hipótesis nula y alternativas

-   Manipular datos con `dplyr`

-   VIsualizar datos con ggplot2

## Método científico

-   Karl Popper

-   Sostiene que no podemos tener certezas sobre fenómenos medibles sino un nivel (medible) de dudas.

-   Pensamiento deductivo. Ciencias empíricas (basados en datos).

-   Las teorías deben ser refutables.

## Formular hipótesis

-   ¿cuál es mi teoría?

-   ¿es refutable?

-   ¿cuales son las hipótesis falsificables que puedo sacar de la teoría?

-   ¿cómo la evaluo?

## Estrategia de evaluación de hipótesis

-   ¿cómo lo vamos a medir cuantitativamente aquello que estamos estudiando?

-   ¿De dónde vienen los datos?

-   ¿cómo se refuta mi teoría?

## La hipótesis nula y alternativas

Usando datos empíricos nunca podemos afirmar nada con absoluta certeza. A lo que podemos aspirar es afirmarlo con cierto nivel de confianza y estimar este nivel. Para ello usamos la hipótesis nula y la alternativa.

1.  Asumo que mi teoría es **incorrecta**. Esta es mi hipótesis nula.
2.  Mi(s) hipótesis alternativa(s) son las que uso si resulta que puedo refutar mi hipótesis nula.

## Ejemplo

Mi teoría es que los hombres son más altos que las mujeres.

-   Hipótesis nula: No hay diferencia de estatura entre hombres y mujeres

-   Hipótesis alternativa: Los hombres son más altos

Notación formal:

$$
H_0: \mu(M) = \mu(H) \\
H_A: \mu(M) < \mu(H) 
$$

## Notación formal

También se usa $H_1$ (y $H_2$, $H_3$ etc.) especialmente si tenemos varias alternativas.

Asimismo es común describirlo en prosa sin notación:

> «nuestra hipótesis nula es que no existe diferencia en estatura entre los dos grupos y la alternativa que los hombres son más altos»

## Manipular datos con dplyr

-   Seleccionar columnas con `select`

-   Seleccionar filas con `filter`

    -   diferencia entre `==` e `=`

    -   Uso de `!=` y `!` en código

-   Renombrar columnas

-   Crear columnas nuevas

-   Cambiar etiquetas de datos categóricos

-   El uso de pipe `|>` y `%>%`

## Visualizar datos con ggplot2

-   Función `ggplot`

-   Función `aes`

-   los `geom_`
